### ISSUE TITLE
Error during installation with composer and php 8

### ISSUE THREAD

**Issue by pascalbott** [pingencom/pingen2-sdk-php#1]
I am trying to install the API via Composer, but I get an error message during the installation:

` [InvalidArgumentException]                                                                                                        
  Package pingencom/pingen2-sdk-php has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - pingencom/pingen2-sdk-php 2.0.0 requires php ^7.4 which does not match your installed version 8.0.11`

Currently using PHP version 8.0.11

**Comment by pingencom** [comment]
That is correct. As the error message states we currently are not yet ready for PHP 8, this is currently in final review and should be published within the next few days.

**Comment by pingencom** [comment]
@pascalbott the new version 2.1.0 has just been released which supports 8.0.x
