### ISSUE TITLE
The price calculator endpoint is missing in the SDK

### ISSUE THREAD

**Issue by roelandkuiper** [pingencom/pingen2-sdk-php#6]
The recently added "price calculator" endpoint is missing in this SDK, when will this be added?

See Pingen v2 API docs:
https://api.v2.pingen.com/documentation#tag/letters.general/operation/letters.price-calculator

**Comment by pingencom** [comment]
Not all endpoints are added to the SDK automatically, only when there is a need and use case for it.
In this case we'll be adding this to the SDK however this will probably only be done in Q1 2023. Please stand by.

**Comment by roelandkuiper** [comment]
I see the endpoint was added, thanks!!
